<div class="container">
  <h3>¿Esta seguro que desea eliminar este registro?</h3>

  <br><br>

  <?php echo Form::open("", "POST") ?>
    <div class="form-group">
      <label>NIT O CEDULA</label>
      <?php echo Form::text('cliente.nit', "class='form-control' readonly", $cliente->nit) ?>
    </div>
  
    <div class="form-group">
      <label>TIPO CLIENTE</label>
      <?php echo Form::dbSelect('cliente.tipocliente_id', 'nombre', null, 'Seleccione el tipo de cliente', "class='form-control' disabled", $cliente->tipocliente_id ) ?>
    </div>
    <div class="form-group">
      <label>NOMBRE DE LA RAZON SOCIAL</label>
      <?php echo Form::text('cliente.nombre', "class='form-control' readonly", $cliente->nombre) ?>
    </div>
  
    <div class="form-group">
      <label>DIRECCIÓN</label>
      <?php echo Form::text('cliente.direccion', "class='form-control' readonly", $cliente->direccion) ?>
    </div>
  
    <div class="form-group">
      <label>NOMBRE DEL REPRESENTANTE LEGAL</label>
      <?php echo Form::text('cliente.nombre_representante_legal', "class='form-control' readonly", $cliente->nombre_representante_legal) ?>
    </div>
  
    <div class="form-group">
      <label>TELEFONO LOCAL</label>
      <?php echo Form::text('cliente.telefono', "class='form-control' readonly", $cliente->telefono) ?>
    </div>
  
    <div class="form-group">
      <label>CELULAR</label>
      <?php echo Form::text('cliente.celular', "class='form-control' readonly", $cliente->celular) ?>
    </div>
  
    <div class="form-group">
      <label>CORREO ELECTRONICO</label>
      <?php echo Form::email('cliente.correo_electronico', "class='form-control' readonly", $cliente->correo_electronico) ?>
    </div>
  
    <div class="form-group">
      <label>Municipio</label>
      <?php echo Form::dbSelect('cliente.tipomunicipio_id', 'nombre', null, 'Seleccione el municipio', "class='form-control' disabled", $cliente->tipomunicipio_id ) ?>
    </div>
    
    <div class="form-group">
      <label>ESTADO DEL CLIENTE</label>
      <?php
        $ar2 = array('1 '=>'ACTIVO','0'=>'INACTIVO');
        echo Form::Select('cliente.activo', $ar2, "class='form-control ' disabled",$cliente->activo);
       ?>
      
    </div>

    <div class="form-group text-right">
      <input type="submit" value="Eliminar" class="btn btn-danger">
      <a href="<?php echo PUBLIC_PATH?>cliente/index" class="btn btn-default">Volver</a>
    </div>
  <?php echo Form::close() ?>
</div>