<div class="container">
  <article class="panel panel-primary">
    <header class="panel-heading">
      <h3 class="panel-title">Listado de clientes</h3>
    </header>
    <section class="panel-body">
      <a href="<?php echo PUBLIC_PATH; ?>cliente/nuevo" class="btn btn-primary btn-sm" title="Nuevo cliente">
        <i class="glyphicon glyphicon-plus"></i>&nbsp;&nbsp;Nuevo cliente
      </a>
      <br><br>
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Nit</th>
            <th>Nombre</th>
            <th>Dirección</th>
            <th>Correo</th>
            <th>Telefono</th>
            <th>Tipo cliente</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($clientes as $cli): ?>
            <tr>
              <td><?php echo $cli->nit ?></td>
              <td><?php echo $cli->nombre ?></td>
              <td><?php echo $cli->direccion ?></td>
              <td><?php echo $cli->correo_electronico ?></td>
              <td><?php echo $cli->telefono ?></td>
              <td><?php echo $cli->getTipocliente()->nombre ?></td>
              <td>
                <a href="<?php echo PUBLIC_PATH; ?>cliente/editar/<?php echo $cli->id ?>" class="btn btn-success btn-sm" title="Editar cliente">
                  <i class="glyphicon glyphicon-pencil"></i>
                </a>
                <a href="<?php echo PUBLIC_PATH; ?>cliente/eliminar/<?php echo $cli->id ?>" class="btn btn-danger btn-sm" title="Eliminar cliente">
                  <i class="glyphicon glyphicon-trash"></i>
                </a>
              </td>
            </tr>
          <?php endforeach ?>
        </tbody>
      </table>
    </section>
  </article>
</div>