<div class="container">
  <h3>¿Esta seguro que desea eliminar este registro?</h3>

  <br><br>

  <?php echo Form::open("", "POST") ?>
  <div class="form-group">
    <label>Tipo ensayo</label>
    <?php echo Form::text('irca.getTipoensayo', "readonly class='form-control'", $irca->getTipoensayo()->nombre ) ?>
  </div>
  <div class="form-group">
    <label>Unidades</label>
    <?php echo Form::text('irca.unidades', "readonly class='form-control'", $irca->unidades) ?>
  </div>
  <div class="form-group">
    <label>Limite inferior</label>
    <?php echo Form::text('irca.limiteinferior', "readonly class='form-control'", $irca->limiteinferior) ?>
  </div>
  <div class="form-group">
    <label>Limite superior</label>
    <?php echo Form::text('irca.limitesuperior', "readonly class='form-control'", $irca->limitesuperior) ?>
  </div>
  <div class="form-group">
    <label>Puntaje riesgo</label>
    <?php echo Form::text('irca.puntajeriesgo', "readonly class='form-control'", $irca->puntajeriesgo) ?>
  </div>
  <div class="form-group text-right">
    <input type="submit" value="Eliminar" class="btn btn-danger">
    <a href="<?php echo PUBLIC_PATH?>irca/index" class="btn btn-default">Volver</a>
  </div>
  <?php echo Form::close() ?>
</div>