<div class="container">
  <article class="panel panel-primary">
    <header class="panel-heading">
      <h3 class="panel-title">Constantes <?php echo $tipoEnsayo->nombre ?></h3>
    </header>
    <section class="panel-body">
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Valor</th>
            <th></th>
          </tr>
          <tbody>
            <?php foreach ($constantes as $cons): ?>
              <tr>
                <td><?php echo $cons->nombre ?></td>
                <td><?php echo $cons->valor ?></td>
                <td class="text-center">
                  <a
                    href="<?php echo PUBLIC_PATH ?>variable/editar_constante/<?php echo $cons->id ?>"
                    class="btn btn-success btn-sm"><i class="glyphicon glyphicon-pencil"></i></a>
                </td>
              </tr>
            <?php endforeach ?>
          </tbody>
        </thead>
      </table>
    </section>
  </article>
  <div class="form-group text-right">
    <a href="<?php echo PUBLIC_PATH?>variable/index" class="btn btn-default">Volver</a>
  </div>
</div>