<div class="container">
  <article class="panel panel-primary">
    <header class="panel-heading">
      <h4 class="panel-title">Formatos ingresados</h4>
    </header>
    <section class="panel-body">
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Código</th>
            <th>Fecha Emision</th>
            <!--<th>Tomador Muestra</th>-->
            <th>Lugar Toma Muestra</th>
            <th>Cliente</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($formatos as $formato): ?>
            <tr>
              <td><?php echo $formato->codigoinformeleyenda." ".$formato->codigoinformeano."-".$formato->codigoinformesecuencial ?></td>
              <td><?php echo $formato->fechaemision ?></td>
              <!--<td><?php //echo $formato->getTomadormuestra()->nombre ?></td>-->
              <td><?php echo $formato->lugartomamuestra ?></td>
              <td><?php echo $formato->getCliente()->nombre ?></td>
              <td>
                  <?echo Html::link("formato/exportarFormato/$formato->id","Exportar","class='btn btn-success'")?>                
              </td>
            </tr>
          <?php endforeach ?>
        </tbody>
      </table>
    </section>
  </article>
</div>