<style>
    .fuenteroja{
        color: red;
    }
</style>
<div class="container">
    <div class="col-md-12 text-right">

        <?
        $t = new Tomadormuestraaccion();
        $at = array();
        $at = $t->find('formato_id=' . $formato->id);
        foreach ($at as $atobj) {
            if ($atobj->usuario_id == $user->id) {
                if ($atobj->tipoaccion_id == 1) {
                    ?>

                    <button id="btnGuardarMemoria" class="btn btn-primary">Guardar memoría</button>
                    <?
                }
            }
        }
        ?>


        <?php //if ($formato->estado > 1 && ($user->tipousuario_id == 1 || $user->tipousuario_id == 3)): ?>
        <!--<button id="btnVistoBno" class="btn btn-success">Dar visto bueno</button>-->
        <?php //endif  ?>
    </div>
    <h2>Memoria de calculo</h2>
    <ul class="nav nav-tabs">
        <li class="active"><a href="#datos">Datos</a></li>
        <li><a href="#memoria">Memoria de calculo</a></li>
        <li><a href="#revision">Revisiones</a></li>
    </ul>


    <div class="tab-content">
        <div id="datos" class="tab-pane fade in active">
            <br>
            <!-- Datos de muestras -->
            <div class="row">
                <div class="col-md-12">
                    <?php foreach ($formato->getTempformatotipoensayo() as $te): ?>
                        <?php
                        if ($te->tipoensayo_id != 2 && $te->tipoensayo_id != 46 &&
                                $te->tipoensayo_id != 3 && $te->tipoensayo_id != 22 &&
                                $te->tipoensayo_id != 20 && $te->tipoensayo_id != 49 &&
                                $te->tipoensayo_id != 8 && $te->tipoensayo_id != 50):
                            ?>


                            <div class="panel panel-primary">
                                <div class="panel-heading"><?php echo $te->getTipoensayo()->nombre ?></div>
                                <div class="panel-body">
                                    <table class="table table-tipo-ensayo" data-tipo-ensayo="<?php echo $te->id; ?>">
                                        <tbody>
                                            <tr>
                                                <?php foreach ($identMuestra as $index => $ident): ?>
                                                    <td>
                                                        <? echo "Muestra" . $ident ?>  
                                                        <?php
                                                        $idMuestra = $muestras[$index]->id;

                                                        //criferlo
                                                        $mmc = new Muestramemoriacalculo();
                                                        $mmcr = array();
                                                        $mmcr = $mmc->find("muestra_id=" . $idMuestra);

                                                        $idTipoEnsayo = $te->getTipoensayo()->id;
                                                        $valor = 0;
                                                        foreach ($mmcr as $omm) {
                                                            if ($omm->tipoensayo_id == $idTipoEnsayo) {
                                                                $valor = $omm->resultado;
                                                                break;
                                                            }
                                                        }
                                                        //criferlo

                                                        echo Form::number(
                                                                "Campo_" . $idTipoEnsayo . "_" . $ident, "class='form-control fullwidth acidez-input' data-muestra_id='$idMuestra' data-tipo_id='$idTipoEnsayo' placeholder='Muestra $ident'", $valor
                                                        )
                                                        ?>
                                                    </td>
                                                <?php endforeach ?>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>

                        <?php endif ?>
                    <?php endforeach ?>
                </div>
            </div>
        </div>
        <!-- Fin Datos de muestras -->
        <div id="memoria" class="tab-pane fade">
            <br>
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-primary">
                        <div class="panel-heading">ACIDEZ</div>
                        <div class="panel-body">
                            <?php
                            View::partial(
                                    'memoria_calculo_modificar/acidez', FALSE, array(
                                'muestras' => $muestras,
                                'constantes' => $acidez->getConstantetipoensayo()
                                    )
                            )
                            ?>
                        </div>
                    </div>

                    <div class="panel panel-primary">
                        <div class="panel-heading">ALCALINIDAD RANGO BAJO</div>
                        <div class="panel-body">
                            <?php
                            View::partial(
                                    'memoria_calculo_modificar/alcalinidad_rango_bajo', FALSE, array(
                                'muestras' => $muestras,
                                'constantes' => $alcalinidadRangoBajo->getConstantetipoensayo()
                                    )
                            )
                            ?>
                        </div>
                    </div>

                    <div class="panel panel-primary">
                        <div class="panel-heading">ALCALINIDAD</div>
                        <div class="panel-body">
                            <?php
                            View::partial(
                                    'memoria_calculo_modificar/alcalinidad', FALSE, array(
                                'muestras' => $muestras,
                                'constantes' => $alcalinidad->getConstantetipoensayo()
                                    )
                            )
                            ?>
                        </div>
                    </div>

                    <div class="panel panel-primary">
                        <div class="panel-heading">DUREZA TOTAL</div>
                        <div class="panel-body">
                            <?php
                            View::partial(
                                    'memoria_calculo_modificar/dureza_total', FALSE, array(
                                'muestras' => $muestras,
                                'constantes' => $durezaTotal->getConstantetipoensayo()
                                    )
                            )
                            ?>
                        </div>
                    </div>

                    <div class="panel panel-primary">
                        <div class="panel-heading">DUREZA CALCICA</div>
                        <div class="panel-body">
                            <?php
                            View::partial(
                                    'memoria_calculo_modificar/dureza_calcica', FALSE, array(
                                'muestras' => $muestras,
                                'constantes' => $durezaCalcica->getConstantetipoensayo()
                                    )
                            )
                            ?>
                        </div>
                    </div>
                    <div class="panel panel-primary">
                        <div class="panel-heading">VARIOS</div>
                        <div class="panel-body">
                            <?php
                            View::partial(
                                    'memoria_calculo_modificar/varios', FALSE, array(
                                'muestras' => $muestras,
                                'constantes' => $varios->getConstantetipoensayo()
                                    )
                            )
                            ?>
                        </div>
                    </div>

                    <div class="panel panel-primary">
                        <div class="panel-heading">CLORUROS</div>
                        <div class="panel-body">
                            <?php
                            View::partial(
                                    'memoria_calculo_modificar/cloruros', FALSE, array(
                                'muestras' => $muestras,
                                'constantes' => $cloruros->getConstantetipoensayo()
                                    )
                            )
                            ?>
                        </div>
                    </div>

                    <div class="panel panel-primary">
                        <div class="panel-heading">MICROBIOLOGÍA</div>
                        <div class="panel-body">
                            <?php
                            View::partial(
                                    'memoria_calculo_modificar/microbiologia', FALSE, array(
                                'muestras' => $muestras,
                                'constantes' => $microbiologia->getConstantetipoensayo()
                                    )
                            )
                            ?>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-1"><br><br></div>
                    </div>
                </div>
            </div>
        </div>


        <!-- Fin Datos de muestras -->
        <div id="revision" class="tab-pane fade">
            <br><br>

            <div class="container-fluid">


                <div class="col-sm-12 center-block" style="margin-left: 0%;">

                    <!-- datos del estudiante -->

                    <div class="panel panel-default panelIndex">
                        <div class="panel-heading titulopanelIndex">
                            <h3 class="panel-title centrar">Revisiones</h3>
                        </div>
                        <? echo Form::open() ?>
                        <div class="panel-body" id="editarusuario">
                            <div class="col-sm-12">
                                Revisión:
                                <? echo Form::text("revision", "class='col-md-12'") ?>

                                <? echo Form::submit("Guardar") ?>
                            </div>

                        </div>
                        <? echo Form::close() ?>

                        <div class="panel-body" id="editarusuario">

                            <table style="width: 100%">
                                <tr style="background-color: #A5D6A7">
                                    <th class="thTablasTituloIndex">Revision</th>
                                    <th class="thTablasTituloIndex">Tomador muestra</th>
                                    <th class="thTablasTituloIndex">Realizado</th> 
                                    <th class="thTablasTituloIndex">Opciones</th> 
                                </tr>
                                <tbody>
                                    <? foreach ($arevisiones as $ar) { ?>
                                        <tr <?
                                        if ($ar->realizado == "N") {
                                            echo "class='fuenteroja'";
                                        }
                                        ?>>
                                            <td class="thTablasVerdes"><? echo $ar->revision ?></td> 
                                            <td class="thTablasVerdes"><?
                                                $t = new Usuario();
                                                $t = $t->find_first($ar->usuario_id);
                                                echo $t->nombrecompleto;
                                                ?></td> 
                                            <td class="thTablasVerdes"><? echo $ar->realizado ?></td>
                                            <td class="thTablasVerdes">
                                                <?
                                                $t = new Tomadormuestraaccion();
                                                $at = array();
                                                $at = $t->find('formato_id=' . $formato->id);
                                                foreach ($at as $atobj) {
                                                    if ($atobj->usuario_id == $user->id) {
                                                        if ($atobj->tipoaccion_id == 1) {
                                                            if ($ar->realizado == "N") {
                                                                $varbutton = "btn-danger";
                                                            } else {
                                                                $varbutton = "btn-success";
                                                            }
                                                            echo Html::link("formato/modrevision/$formato->id/$ar->id", "Realizado", "class='btn " . $varbutton . "'");
                                                        }
                                                    }
                                                }
                                                ?>                            


                                            </td>
                                        </tr>
<? } ?>
                                </tbody>
                            </table>         

                        </div>

                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

<script>
    $(document).ready(function () {




        var memoriaCalculo = [2, 46, 3, 22, 20, 49, 8, 50];
        var tipoEnsayo = [];
        var muestras_ids = [];
        var formato_id = 0;
<?php
//eliminar lo que hay


$arrt = array(2, 46, 3, 22, 20, 5, 21, 29, 8, 50);

foreach ($formato->getTempformatotipoensayo() as $te) {
    $ban = 0;
    foreach ($arrt as $d) {
        if ($d == $te->tipoensayo_id) {
            $ban = 1;
            break;
        }
    }
    if ($ban == 0) {
        echo 'tipoEnsayo.push(' . $te->tipoensayo_id . ');';
    }
}
foreach ($muestras as $mst) {
    echo 'muestras_ids.push(' . $mst->id . ');';
}

echo 'formato_id=' . $formato->id . ";";
?>

        //console.log(tipoEnsayo);
        //console.log(muestras_ids);

        $(".nav-tabs a").click(function () {
            $(this).tab('show');
        });

        $('#btnGuardarMemoria').on('click', function (e) {
            e.preventDefault();

            //eliminar lo que hay
            arrayDataEliminar = [];
            for (i = 0; i < muestras_ids.length; i++) {
                var dataeliminar = {
                    muestra_id: muestras_ids[i],
                }
                arrayDataEliminar.push(dataeliminar);
            }

            $.ajax({
                url: '<?php echo PUBLIC_PATH ?>memoriarest/0',
                type: 'DELETE',
                contentType: 'application/json',
                data: JSON.stringify(arrayDataEliminar)
            }).done(function (data)
            {
                //alert("Datos enviados con éxito");
                //window.location = "formato/modificar/" + formato_id;
            }).complete(function (data) {
                //alert("hola");
                // alert("Datos eliminados con éxito");
                //window.location = "../modificar/" + formato_id;
            });

            var ajaxCalls = [];
            var functions = [];
            var functions = [
                GenerateJsonAcidez,
                GenerateJsonAlcalinidad,
                GenerateJsonAlcalinidadRangoBajo,
                GenerateJsonCloruros,
                GenerateJsonDurezaCalcica,
                GenerateJsonDurezaTotal,
                GenerateJsonMicrobiologia1,
                GenerateJsonMicrobiologia2,
                GenerateJsonMicrobiologia3,
                GenerateJsonCalcio,
                GenerateJsonDurezaMagnesio,
                GenerateJsonMagnesio
            ];

            arrayData = [];
            muestras_ids.forEach(function (muestra_id) {
                tipoEnsayo.forEach(function (tipoEnsayo_id) {
                    var input = $([
                        'input[data-muestra_id=',
                        muestra_id, ']',
                        '[data-tipo_id=',
                        tipoEnsayo_id, ']'
                    ].join(''));

                    if (input && tipoEnsayo_id != 2) {
                        
                        var res = input.val();
                        /*if(tipoEnsayo_id==27 || tipoEnsayo_id==15){
                            res=res/10;
                        }*/
                        
                        data = {
                            muestra_id: muestra_id,
                            tipoensayo_id: tipoEnsayo_id,
                            resultado: res
                        };
                        arrayData.push(data);
                        //}));
                    }
                });

                functions.forEach(function (fn) {
                    data =
                            fn(muestra_id)
                            ;
                    arrayData.push(data);
                    //}));
                });
            });

            $.ajax({
                url: '<?php echo PUBLIC_PATH ?>memoriarest/',
                type: 'POST',
                contentType: 'application/json',
                data: JSON.stringify(arrayData),
                 beforeSend: function () {
                    $(".container").html("<img src='<?echo PUBLIC_PATH."img/loader.gif"?>'/>Espere un momento...");
                },
            }).done(function (data)
            {
                //alert("Datos enviados con éxito");
                //window.location = "formato/modificar/" + formato_id;
            }).complete(function (data) {
                //alert("hola");
                /*if (<?php echo $formato->estado ?> == 1) {
                 $.ajax({
                 url: "<?php echo PUBLIC_PATH ?>formato/actualizar_estado",
                 method: 'POST',
                 data: {
                 formato_id: "<?php echo $formato->id ?>",
                 usuario_id: "<?php echo $user->id ?>",
                 tipousuario_id: "<?php echo $user->tipousuario_id ?>"
                 }
                 });
                 }
                 ;*/
                alert("Datos enviados con éxito");
                window.location = "../modificar/" + formato_id;
            });
        });


        $('#btnVistoBno').on('click', function (e) {
            e.preventDefault();

            $.ajax({
                url: "<?php echo PUBLIC_PATH ?>formato/actualizar_estado",
                method: 'POST',
                data: {
                    formato_id: "<?php echo $formato->id ?>",
                    usuario_id: "<?php echo $user->id ?>",
                    tipousuario_id: "<?php echo $user->tipousuario_id ?>"
                },
                success: function (result) {
                    alert('Visto bueno almacenado correctamente');
                },
                error: function (error) {
                }
            });
        });

    });
</script>